### ISSUE TITLE
Usage error

### ISSUE THREAD

**Issue by kingroryg** [slowjud/FFT#1]
Are you sure the `gem install fft` works correctly. I required this module and received the following error : 
```
ruby lib/filter.rb
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fft (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from lib/filter.rb:1:in `<main>'
```

I tested in `irb` as well. It gives the following error there : 
```
¯\_(ツ)_/¯  $  irb
irb(main):001:0> require 'fft'
LoadError: cannot load such file -- fft
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/local/bin/IRB:11:in `<main>'
irb(main):002:0> 
```

**Comment by slowjud** [comment]
This gem was abandoned many (almost 7) years ago. Sorry but it would probably be easier to rewrite it than ge tit working with a current system.

**Comment by kingroryg** [comment]
Ohh ! alright. no problems. :)
